version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5433:5432 
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 9001:8080